### ISSUE TITLE
Compilation errors mocking generic interfaces

### ISSUE THREAD

**Issue by ssitwell** [connorivy/MockMe#42]
When trying to use mocks for Microsoft.Extensions.Logging ILogger, generated mock files result in compilation errors.

CreateCallTracker, Setup, Assert, methods have the following error:

`CS0116	A namespace cannot directly contain members such as fields, methods or statements`

Same methods also are having issues with generic parameter TCategoryName:

`CS0246	The type or namespace name 'TCategoryName' could not be found (are you missing a using directive or an assembly reference?)`

What looks like a static constructor for the mock has the error:

`CS1520	Method must have a return type`		

Also created dummy code using IList with a class as the generic parameter and resulted in similar errors.

**Comment by connorivy** [comment]
ah okay thanks for reporting this issue.

I can't believe I don't have a test for generic interfaces. I should be able to get around to fixing this today. Will keep you posted.

**Comment by connorivy** [comment]
@ssitwell 

I have partially fixed this. Your original use case of wanting to mock ILogger<T> should work using the new 1.1.2 release. However, the second example you mentioned, mocking IList<T> is a bit more complicated and actually relates to a different open issue https://github.com/connorivy/MockMe/issues/40.

The IList<T> implements multiple conflicting interfaces (i.e. GetEnumerator() is implemented multiple times in the interface itself and in interfaces that it implements). Support for this case will come soon, but like I said before. The more general cases of generic interfaces should work. Feel free to reopen this issue if that is not the case.
